version: '3'
services:
  demo:
    image: demo
    container_name: demo
    hostname: demo
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
networks:
  default:
    name: demo-net
    external: true